Create CODE_OF_CONDUCT.md
OpenPLF/oplf pull request #16
Opened 2023-05-02 05:05 UTC by santosomar

Fixes #15

2023-05-02 20:49 UTC, tschmidtb51 reviewed
That sounds a lot like the one from http://contributor-covenant.org/version/1/4 (If so, I guess we should cite them as source.)

BTW: There are two other sections, that we use in [Secvisogram](https://github.com/secvisogram/secvisogram/blob/main/CONTRIBUTING.md#code-of-conduct)

2023-05-03 04:28 UTC, santosomar commented
Thank you @tschmidtb51 ! I updated the file. This Code of Conduct is adapted from the [Contributor Covenant][homepage],
version 2.1, available at
[https://www.contributor-covenant.org/version/2/1/code_of_conduct.html][v2.1].

2023-05-04 21:44 UTC, merged

2023-05-04 21:45 UTC, tschmidtb51 requested changes
I guess we need to add the contact info

2023-05-04 21:45 UTC, tschmidtb51 commented on CODE_OF_CONDUCT.md
> +[INSERT CONTACT METHOD].
I guess we need to insert a contact method here...